# Use an official Python runtime as a parent image
FROM ubuntu:latest

# Set the working directory
WORKDIR /app

# Install necessary packages
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    nodejs \
    npm \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install pm2 globally
RUN npm install -g pm2

# Copy the current directory contents into the container at /app
COPY . .

# Install Python dependencies
RUN pip3 install -r requirements.txt

# Install Node.js dependencies for the React app
RUN npm install

# Expose the ports for FastAPI and React
EXPOSE 9400
EXPOSE 3000

# Start both applications using pm2
CMD ["pm2-runtime", "start", "backend/websocket/src/App.js", "--name", "react-app", "--interpreter", "node", "--", "start", "&&", "pm2-runtime", "start", "backend/websocket/fastapi_websocket.py", "--name", "fastapi-app", "--interpreter", "python3", "-m", "uvicorn", "fastapi_websocket:app", "--host", "0.0.0.0", "--port", "9400"]